### PR TITLE
Module and testing

### PR DESCRIPTION
**Pull request by TasmanGC**
I think these changes will help the implementation of testing functions, which is what I propose to contribute to this project. 

Pending approval, I would occasionally write:

- unit tests
- integration tests
- mock objects for server responses etc

### CODE REVIEW

**Comment by LSgeo** [comment]
Looks great, thanks for the contribution. Can you please:

1. Format all files with black (now available as a vscode extension if that's your flavour), and
2. Squash commits as seems suitable (e.g., at least the two .gitignore commits).

I can squash them all automatically, but can't do the formatting via Github. 
Cheers!

**Comment by TasmanGC** [comment]
Hey I think I addressed you're concerns. Please review.

**Comment by LSgeo** [comment]
Please format with black, otherwise looks lgtm 👍🏻

**Comment by TasmanGC** [comment]
Hey thanks see above.

**Pull request merged**
